# Generated by Django 5.0.1 on 2024-01-22 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message_content', models.TextField(null=True)),
                ('From_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_message', to='shop.registration')),
                ('To_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_message', to='shop.registration')),
            ],
        ),
    ]
