# Generated by Django 5.0.1 on 2024-01-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_userprofile_password_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('Message_content', models.TextField(null=True)),
            ],
        ),
    ]
